on:
  push:
    branches:
      - development

name: 🚀 Deploy development branch on push

jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: cs2410-web01pvm.aston.ac.uk
        username: u-220216407  
        password: ${{ secrets.ftp_password }} 
