# Controls when the action will run. 
name: tests
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [development, main]

# Define the jobs to run
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      # Define a service container for MySQL
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: team_project_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-req=ext-imagick
        working-directory: WoodLess
      
      - name: Generate key for testing
        run: php artisan key:generate --env=testing
        working-directory: WoodLess

      - name: Run database migrations for testing
        run: php artisan migrate --env=testing --force
        working-directory: WoodLess

      - name: Run Laravel Tests
        run: php artisan test
        working-directory: WoodLess
